### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by felddy**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-generic.git`](https://github.com/cisagov/skeleton-generic.git)

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
☕️

**Comment by mcdonnnj** [comment]
Had a thought a bit later, but we may want to revert the code in the `lint` workflow to generate and use a custom `.pre-commit-config.yaml` at https://github.com/cisagov/skeleton-packer/blob/351db5adff2347d7ff085c0c4306ebda6cc041bb/.github/workflows/build.yml#L94-L110 to just using the `.pre-commit-config.yaml` file as-is now that the `terraform_validate` hook is disabled upstream.

**Review by jsf9k — APPROVED** [review]
Put that in your pipe and smoke it!

**Comment by dav3r** [comment]
> Had a thought a bit later, but we may want to revert the code in the `lint` workflow to generate and use a custom `.pre-commit-config.yaml` at
> 
> https://github.com/cisagov/skeleton-packer/blob/351db5adff2347d7ff085c0c4306ebda6cc041bb/.github/workflows/build.yml#L94-L110
> 
> to just using the `.pre-commit-config.yaml` file as-is now that the `terraform_validate` hook is disabled upstream.

This makes sense to me, though there's no big rush to do this- we can always tack it on to a future PR (e.g. the next time we update all of the pre-commit hook versions).

**Review by dav3r — APPROVED** [review]
🌳

**Pull request merged**
