### PR TITLE
Use FQCNs

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request modifies the Ansible code to use fully qualified collection names (FQCNs) for all Ansible modules.

## 💭 Motivation and context ##

FQCNs are the future of Ansible.

## 🧪 Testing ##

All `pre-commit` hooks pass.  I have also successfully built AMIs using these same changes in cisagov/teamserver-packer#27 and cisagov/kali-packer#61, and cisagov/nessus-packer#25.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Comment by jsf9k** [comment]
There is no need to wait for the next Kraken to merge this PR.  I will handle any [lineage](https://github.com/cisagov/action-lineage) PRs that ensue.

**Review by dav3r — APPROVED** [review]
⛽ 🔥

**Review by hillaryj — APPROVED** [review]
🐨

**Review by mcdonnnj — APPROVED** [review]
image

**Pull request merged**
