### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-generic.git`](https://github.com/cisagov/skeleton-generic.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by jsf9k** [comment]
@mcdonnnj - I can take a look at these failures if you want.

**Comment by mcdonnnj** [comment]
> 
> 
> @mcdonnnj - I can take a look at these failures if you want.

Ah, sorry. I figured I knew what was wrong when I initially looked at the PR earlier, so I ended up resolving it before I saw your comment. Let me know if you think there's a better/more preferable way.

**Review by dav3r — APPROVED** [review]

**Comment by jsf9k** [comment]
> Ah, sorry. I figured I knew what was wrong when I initially looked at the PR earlier, so I ended up resolving it before I saw your comment. Let me know if you think there's a better/more preferable way.

No worries.  I wasn't sure what was wrong, so I was just offering to help if you were also on the high seas.

**Review by jsf9k — APPROVED** [review]
Huzzah!

**Pull request merged**
