### PR TITLE
Fix repeated typo

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request fixes a typo that was copied and pasted many times in #74.

## 💭 Motivation and context ##

If we don't fix this typo then we get a syntax error.

## 🧪 Testing ##

All `pre-commit` hooks pass.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
I cannot believe I missed this on review -,-

**Comment by mcdonnnj** [comment]
This highlights how we need to enable `terraform validate` checking as soon as we migrate to Terraform 0.13+.

**Comment by jsf9k** [comment]
> I cannot believe I missed this on review -,-

In my defense, the shift key on my keyboard is acting up today.  Still pretty bone-headed of me to make the mistake in the first place.  I blame society, as always.

**Review by dav3r — APPROVED** [review]
🙈

**Pull request merged**
