### PR TITLE
Move to version 3.x of the AWS Terraform provider

### PR DESCRIPTION
**Pull request by dav3r**
# 

## 🗣 Description
This pull request upgrades the Terraform code to use to version 3 of the Terraform AWS provider.

## 💭 Motivation and Context

Version 3 of the AWS provider has been out for a while. We don't want to get left behind.

## 🧪 Testing
* For `terraform-build-user`, I successfully ran `terraform apply` and confirmed that the `build-skeleton-packer` user was properly destroyed and then re-created (there have been some significant Terraform changes since that user was initially created, so this was expected).
* For `terraform-post-packer`, I successfully ran `terraform apply` in both Staging and Production Terraform workspaces.  I then ran `terraform destroy` in the Production workspace, since I don't think there's any real Production need for those permissions to the `skeleton-packer` AMI (if there is, they can easily be restored later).
* All pre-commit hooks pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)
- [x] Provider upgrade

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Yes!

**Review by mcdonnnj — APPROVED** [review]
Onward and upward!

**Review by hillaryj — APPROVED** [review]
🦖

**Review by felddy — APPROVED** [review]
Holy cannoli!  I can't believe me eyes! 👀

**Pull request merged**
